### ISSUE TITLE
Question: Is this required when using Appium 1.6.3+XCode 8.2.1+iOS 10?

### ISSUE THREAD

**Issue by vsadineni1** [appium/authorize-ios#10]
Question: Is this required when using Appium 1.6.3+XCode 8.2.1+iOS 10?

When I am running tests against iOS10, I see a popup on Mac asking
**"Do you want to allow incoming connections"**

Is it the goal of authorize-ios to supress this alert? 

Or do you know if there is a way to suppress this alert?

**Comment by imurchie** [comment]
This package will not suppress that alert. You need to figure out what that alert is being caused by.
